apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-stack
  namespace: hypermine-development
spec:
  replicas: 1

  selector:
    matchLabels:
      app: redis-stack
  template:
    metadata:
      labels:
        app: redis-stack
    spec:
      containers:
        - name: redis-stack
          image: redis/redis-stack-server
          resources:
            limits:
              memory: "256Mi"
              cpu: "50m"
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-stack-service
  namespace: hypermine-development
spec:
  type: NodePort
  selector:
    app: redis-stack
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
